### ISSUE TITLE
Suburb01 dataset cam0 

### ISSUE THREAD

**Issue by zlthaha** [GREAT-WHU/GREAT-Dataset#1]
When I downloaded the Suburb01 dataset, I found that cam0 seemed to be missing a lot of images, fewer than the timestamps

**Comment by Asrumgya** [comment]
We found that the images were lost during the file compression process. The OneDrive link for suburb-01 has been updated, and the file is now available for download.

**Comment by Asrumgya** [comment]
We found that the images were lost during the file compression process. The OneDrive link for suburb-01 has been updated, and the file is now available for download.
